# Generated by Django 5.0.1 on 2025-07-03 02:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="expertise_area",
            field=models.CharField(
                blank=True, help_text="Area of expertise for judges", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="grade_level",
            field=models.CharField(
                blank=True, help_text="Grade level or year", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="school_organization",
            field=models.CharField(
                blank=True, help_text="School or organization name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="years_experience",
            field=models.PositiveIntegerField(
                blank=True, help_text="Years of relevant experience", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Email verification status"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("judge", "Judge"),
                    ("admin", "Admin"),
                ],
                default="student",
                help_text="Select your role in the platform",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Tell us about yourself (max 500 characters)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Your date of birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="Your first name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, help_text="Your last name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Your contact phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture",
                null=True,
                upload_to=accounts.models.user_profile_image_path,
            ),
        ),
    ]
