# Generated by Django 5.0.1 on 2025-07-03 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_accountdeactivation_reactivationrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reactivationrequest",
            name="reviewed_by",
        ),
        migrations.DeleteModel(
            name="AccountDeactivation",
        ),
        migrations.DeleteModel(
            name="ReactivationRequest",
        ),
    ]
